### ISSUE TITLE
`renault-api charge stop` not working with Renault Zoe E-Tech R110

### ISSUE THREAD

**Issue by mathieucarbou** [hacf-fr/renault-api#763]
Hello,
I need a way to remotely start and stop charging the car battery. I saw this api but it does not seem to work with my Zoe. I was wondering if there is a compatibility chart somewhere, and also if there is a way to remotely start/stop charging the Zoe R110.
Thanks!

```
> Downloads % renault-api status
lock status: VNEXT an internal error occured while processing request : 403 FORBIDDEN
res state: Access is denied for this resource
----------------  ------------------------------
Battery level     52 %
Last updated      2023-01-05 16:16:03
Available energy  22 kWh
Range estimate    161 km
Plug state        PlugState.PLUGGED
Charging state    ChargeState.CHARGE_IN_PROGRESS
Charge rate       0.07 kW
Time remaining    1005 min
Total mileage     1348.55 km
Fuel autonomy     0.0 km
Fuel quantity     0.0 L
GPS Latitude      
GPS Longitude    
GPS last updated  2023-01-05 11:15:15
HVAC status       off
----------------  ------------------------------

> Downloads % renault-api vehicle 
Registration    Brand    Model    VIN
--------------  -------  -------  -----------------
XXXXXXX         RENAULT  ZOE     XXXXXXXXXXXX

> Downloads % renault-api charge stop
{'action': 'stop'}
```

Charge does not stop.

**Comment by epenet** [comment]
There is no official documentation available, so it's all trial and error.

This is the list of all endpoints: https://renault-api.readthedocs.io/en/latest/endpoints.html
Some have notes (like https://renault-api.readthedocs.io/en/latest/endpoints.html#actions-hvac-start)

**Comment by mathieucarbou** [comment]
Oh boy! I feel your pain! 
So actually the current impl works with some cars, but, like the HVAC option, which is also not working on my Zoe from Home Assistant by the way, the stop charge action might also just not work / not be implemented for the Zoe E-Tech R110, or might work but with a different http call or payload, but we don't know ?

**Comment by epenet** [comment]
Exactly...

If the "stop" action works from the phone app, and you are able to trace the API call, then I am happy to add it in.
However, my own trace tools have stopped working due to Android security settings so I can no longer trace the calls.

I really with the API was properly documented by Renault!

**Comment by mathieucarbou** [comment]
I wish there were such button ;-) I can only start the HVAC, not even stop it :-(

If I want to test some requests the right way would be like that ?

`> renault-api --debug --json http post /commerce/v1/accounts/<UUID>/kamereon/kca/car-adapter/v1/cars/<MY_VIN>/actions/charging-start {"data":{"type": "ChargingStart","attributes":{"action":"cancel"}}}`

**Comment by mathieucarbou** [comment]
ok but if I try with this payload, I don't get the error:" `'{"data":{"type": "ChargingStart","attributes":{"action":"stop"}}}'. So I guess the bad request is because the cancel action is wrong ;-) Got my answer I think.

**Comment by mathieucarbou** [comment]
@epenet : I have installed Mobilize Smart Charge. 
And it turns out that, through this app, I can start a charge (what they call boost charge) and click on cancel after to stop it. And it actually works through the app. BUT...
- The stop takes time because the request does not seem to be received by the vehicule immediately (I would say about 30 sec).
- it can also fail if the rate limit is reached on the account, so the app displays that the charge has stopped, but it actually continues

![https://i.imgur.com/OhUC3DZ.png](https://i.imgur.com/OhUC3DZ.png)

**Comment by mathieucarbou** [comment]
I've checked their APK. They have left the debug settings activated:
```xml
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <debug-overrides>
        <trust-anchors>
            <certificates src="system" />
            <certificates src="user" />
        </trust-anchors>
    </debug-overrides>
</network-security-config>
```
So it should be possible to use an https proxy with a user certificate installed and trusted on android to decrypt all ssl com from the app.

**Comment by mathieucarbou** [comment]
my attempt was not successful... So with HA, I am still able to auto start a charge, but not stop it :-(

**Comment by mathieucarbou** [comment]
Com is done with these hosts. I think they have a B2B com.
![image](https://user-images.githubusercontent.com/61346/211153561-36e4bf32-de4e-410d-9c6d-f6550c0d8a37.png)

**Comment by mathieucarbou** [comment]
@epenet : I found a way to remotely stop the charge.

The trick is to `charge_set_schedules ` service (I am using home assistant) and send a schedule with a duration of 1 minute. For example:
```
      schedules:
        - id: 1
          activated: true
          monday:
            startTime: T05:00Z
            duration: 1
          tuesday:
            startTime: T05:00Z
            duration: 1
          wednesday:
            startTime: T05:00Z
            duration: 1
          thursday:
            startTime: T05:00Z
            duration: 1
          friday:
            startTime: T05:00Z
            duration: 1
          saturday:
            startTime: T05:00Z
            duration: 1
          sunday:
            startTime: T05:00Z
            duration: 1
```
So I have a solution now to automatically start and stop the charge depending in the solar production.
